const productData = [
  {
    img: "/Image/Rectangle 3.png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (2).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3.png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "Out of Stock",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Unpublish",
    status: "Unpublished",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "publish",
    status: "published",
  },
];

export default productData;
