const productData = [
  {
    img: "/Image/Rectangle 3.png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 12 Pro",
    category: "Gadgets",
    price: "₦725,000.00",
    stock: "12",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Published",
  },
  {
    img: "/Image/Rectangle 3 (2).png",
    name: "POLO T-SHIRT",
    category: "Fashion",
    price: "₦125,000.00",
    stock: "120",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Unpublished",
  },
  {
    img: "/Image/Rectangle 3 (2).png",
    name: "POLO T-SHIRT",
    category: "Fashion",
    price: "₦125,000.00",
    stock: "Out of Stock",
    discount: "₦0.00",
    value: "₦0.00",
    action: "Publish",
    status: "Unpublished",
  },
  {
    img: "/Image/Rectangle 3 (2).png",
    name: "POLO T-SHIRT",
    category: "Fashion",
    price: "₦125,000.00",
    stock: "Out of Stock",
    discount: "₦0.00",
    value: "₦0.00",
    action: "Publish",
    status: "Unpublished",
  },
  {
    img: "/Image/Rectangle 3.png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 12 Pro",
    category: "Gadgets",
    price: "₦725,000.00",
    stock: "12",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 13 Pro",
    category: "Gadgets",
    price: "₦1,225,000.00",
    stock: "8",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Published",
  },
  {
    img: "/Image/Rectangle 3 (1).png",
    name: "iPhone 12 Pro",
    category: "Gadgets",
    price: "₦725,000.00",
    stock: "12",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Published",
  },
  {
    img: "/Image/Rectangle 3 (2).png",
    name: "POLO T-SHIRT",
    category: "Fashion",
    price: "₦125,000.00",
    stock: "120",
    discount: "₦0.00",
    value: "₦50,000.00",
    action: "Publish",
    status: "Unpublished",
  },
];

export default productData;
